### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by michaeljones** [cultureamp/elm-css-modules-loader#15]
We love this library and we're hoping to update to Elm 0.19 as I'm sure you are too. Do you know if the approach with this module & webpack loader will continue to work in Elm 0.19 yet?

Can I be of any assistance with the update? I'm not hugely experienced but keen to help!

Thanks.

**Comment by jasononeil** [comment]
We're working on it! (More specifically, @sentience has already begun working on it)

Because of the optimizations that happen to compiled code in Elm 0.19, the API will need to change somewhat. We'd definitely appreciate your feedback once the new version is ready - or close to ready.

**Comment by michaeljones** [comment]
Thanks for the update. Good to know :)

**Comment by michaeljones** [comment]
Hey, I don't want to be a bother, but I'm keen to hear what the current situation is if you have time to share. I can see the commit on the Elm 0.19 branch. It looks hopeful. 

I would be grateful if there is any kind of alpha or anything that we can go with here but I understand you are busy with your own work along with the 0.19 switch.

**Comment by sentience** [comment]
Updating this is the first step in our 0.19 upgrade, and we're working on it actively. Since we're using a couple of post-compile transformations on our Elm, we've realised that we can implement each of these as a Babel plugin so we can run all of them in a single Babel loader pass.

What this means is that the update to this package, when in comes, is likely to take the form of a Babel plugin to be used with the Babel loader rather than a full-fledged webpack loader.

Rough estimate, I'd say you can expect something within a week or so at the outside.

**Comment by michaeljones** [comment]
Thanks! I really appreciate you taking the time to provide an update. That all sounds very reasonable.

**Comment by michaeljones** [comment]
Fantastic, thanks! I confess I copied some of the code into our code base over the weekend and it all seems to be working for us :) Thank again!
